# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170421_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to=settings.AUTH_USER_MODEL),
        ),
    ]
